### PR TITLE
Add support for upper and mixed-case bbcode tags

### PR DESCRIPTION
**Pull request by dpolivy**
The current parser only handles fully lowercase bbcode tags. This change
augments the existing functionality to essentially make the bbcode tag
detection case insensitive, for cases where you may have upper or
mixed-cased tags in your source content.

I'm not enough of a bbcode expert to know whether upper/mixed case tags are 'legal', but I have some source content with that formatting, and so needed these changes in order to make the module fully compatible for my purposes. Hopefully you find the change useful and want to pull it back into your master copy.

I also added a few quick tests to verify all is working well.

Let me know if you have any questions.

Dan

### CODE REVIEW

**Comment by dpolivy** [comment]
Also, I just noticed in GitHub that my editor was a bit aggressive in removing whitespace from the end of lines -- that didn't show up in my difftool so I didn't catch it initially. Let me know if you'd prefer I revert to preserve what you had originally.

**Comment by ncb000gt** [comment]
No worries. LGTM.

Thanks.

**Comment by dpolivy** [comment]
Great! Let me know when you get a chance to push the update to npm and I'll switch back to the 'official' release.

**Comment by ncb000gt** [comment]
Done. :) Enjoy!

**Pull request merged**
